### ISSUE TITLE
NPE when comparing doubles on 3.8.0

### ISSUE THREAD

**Issue by vguna** [joel-costigliola/assertj-core#1015]
#### Summary
Comparing two different objects with same attributes using `isEqualToIgnoringGivenFields` leads to NPE.

#### Example

```java
java.lang.NullPointerException
	at org.assertj.core.util.DoubleComparator.compare(DoubleComparator.java:28)
	at org.assertj.core.util.DoubleComparator.compare(DoubleComparator.java:17)
	at org.assertj.core.internal.Objects.propertyOrFieldValuesAreEqual(Objects.java:662)
	at org.assertj.core.internal.Objects.isEqualToIgnoringGivenFields(Objects.java:640)
	at org.assertj.core.internal.Objects.assertIsEqualToIgnoringGivenFields(Objects.java:613)
	at org.assertj.core.api.AbstractObjectAssert.isEqualToIgnoringGivenFields(AbstractObjectAssert.java:199)
```

#### Java 8 specific ?
I don't think so....

**Comment by vguna** [comment]
Seems that it has been introduced with 3.7.0. 3.6.2 is working fine.

**Comment by joel-costigliola** [comment]
Thanks for reporting this, you can use your own non buggy `DoubleComparator` with [usingComparatorForType](http://joel-costigliola.github.io/assertj/assertj-core-news.html#assertj-core-2.4.0-usingComparatorForType).

**Comment by vguna** [comment]
Thank _you_ for such a nice testing framework :)! I'm lazy and just stick with 3.6.2, but thanks for the hint ;).

**Comment by joel-costigliola** [comment]
@vguna no problem, thanks for the king words
