### ISSUE TITLE
Build failing: ObjectAssert_extracting_Test.should_allow_to_specify_type_comparator_after_using_extracting_on_object)

### ISSUE THREAD

**Issue by alb-i986** [joel-costigliola/assertj-core#1113]
#### Summary
The build is failing on my machine, when running mvn clean test.
The test `ObjectAssert_extracting_Test.should_allow_to_specify_type_comparator_after_using_extracting_on_object` is failing with the following error:

```
[ERROR] Tests run: 5, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.009 s <<< FAILURE! - in org.assertj.core.api.object.ObjectAssert_extracting_Test
[ERROR] should_allow_to_specify_type_comparator_after_using_extracting_on_object(org.assertj.core.api.object.ObjectAssert_extracting_Test)  Time elapsed: 0.006 s  <<< ERROR!
org.assertj.core.util.introspection.IntrospectionError: 

Can't find any field or property with name 'name'.
Error when introspecting properties was :
- No getter for property 'name' in org.assertj.core.api.object.ObjectAssert_extracting_Test$Person 
Error when introspecting fields was :
- Unable to obtain the value of the field <'name'> from <org.assertj.core.api.object.ObjectAssert_extracting_Test$Person@26f93beb>, check that field is public.
	at org.assertj.core.api.object.ObjectAssert_extracting_Test.should_allow_to_specify_type_comparator_after_using_extracting_on_object(ObjectAssert_extracting_Test.java:86)
Caused by: org.assertj.core.util.introspection.IntrospectionError: Unable to obtain the value of the field <'name'> from <org.assertj.core.api.object.ObjectAssert_extracting_Test$Person@26f93beb>, check that field is public.
	at org.assertj.core.api.object.ObjectAssert_extracting_Test.should_allow_to_specify_type_comparator_after_using_extracting_on_object(ObjectAssert_extracting_Test.java:86)
Caused by: java.lang.IllegalAccessException: can not accessname because it is not public
	at org.assertj.core.api.object.ObjectAssert_extracting_Test.should_allow_to_specify_type_comparator_after_using_extracting_on_object(ObjectAssert_extracting_Test.java:86)
```

```
$ mvn -v
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=516m; support was removed in 8.0
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: /opt/apache-maven
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /opt/jdk/jdk1.8.0_144/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-98-generic", arch: "amd64", family: "unix"
```

**Comment by alb-i986** [comment]
PS: If I run the same test from IDEA, it passes (uhm?)

**Comment by joel-costigliola** [comment]
weird, I use linux and the tests pass, our environment are really close !
```
mvn -v
~/prog/assertj/assertj-core-3.x ∙ mvn -v
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T20:58:13+13:00)
Maven home: /home/joel/prog/apache-maven-3.5.2
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /home/joel/prog/java/jdk1.8.0_144/jre
Default locale: en_NZ, platform encoding: UTF-8
OS name: "linux", version: "4.4.0-98-generic", arch: "amd64", family: "unix"
```

**Comment by joel-costigliola** [comment]
The builds pass on Travis CI server.
