### ISSUE TITLE
`isEqualToComparingFieldByFieldRecursively()` throws Exception when using percentage '%' in string field

### ISSUE THREAD

**Issue by hennes-maertins** [joel-costigliola/assertj-core#1136]
#### Summary

I have got a test example using the method `isEqualToComparingFieldByFieldRecursively()`. I expect this test to fail but a `MissingFormatArgumentException` is thrown instead.

#### Example

This is my test code:
```java
import static org.assertj.core.api.Assertions.assertThat;

import org.junit.Test;

public class PercentageTest
{
    private static class Foo
    {
        String value;
    }

    @Test
    public void testPercentage() throws Exception
    {
        Foo foo1 = new Foo();
        foo1.value = "foo";

        Foo foo2 = new Foo();
        foo2.value = "%foo";

        assertThat(foo1).isEqualToComparingFieldByFieldRecursively(foo2);
    }
}
```

This is the exception with stacktrace:
```
java.util.MissingFormatArgumentException: Format specifier '%f'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.assertj.core.util.Strings.formatIfArgs(Strings.java:92)
	at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:61)
	at org.assertj.core.error.BasicErrorMessageFactory.create(BasicErrorMessageFactory.java:110)
	at org.assertj.core.internal.Failures.failure(Failures.java:116)
	at org.assertj.core.internal.Objects.assertIsEqualToComparingFieldByFieldRecursively(Objects.java:713)
	at org.assertj.core.api.AbstractObjectAssert.isEqualToComparingFieldByFieldRecursively(AbstractObjectAssert.java:647)
	at PercentageTest.testPercentage(PercentageTest.java:26)
```

#### Java 8 specific ?

I have tested this with AssertJ versions 2.6.0 and 3.8.0.

**Comment by joel-costigliola** [comment]
Good catch, we should escape `%` when formatting the error.
