### ISSUE TITLE
Extracting String value using AutoCloseableSoftAssertion throws  java.lang.ClassFormatError

### ISSUE THREAD

**Issue by mavinkurve** [joel-costigliola/assertj-core#1146]
#### Summary
Extracting string values from map throws following exception:

Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.assertj.core.internal.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:459)
	at org.assertj.core.internal.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
	... 39 more
Caused by: java.lang.ClassFormatError: Duplicate method name&signature in class file org/assertj/core/api/ObjectArrayAssert$$EnhancerByCGLIB$$2a693b8d$$EnhancerByCGLIB$$e518c7e6
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	... 45 more

#### Example

```java
        Map<String,String> data = new HashMap<>();
        data.put("one","1");
        data.put("two","2");
        data.put("three","3");
        try (final AutoCloseableSoftAssertions softly = new AutoCloseableSoftAssertions()) {
            softly.assertThat(data).extracting("one").containsExactly("1");
        }
```

#### Java 8 specific ?
No

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
@mavinkurve thanks for reporting this, which version are you using?

**Comment by joel-costigliola** [comment]
maybe it is time to use byte buddy as this is really hard to debug which poor exception information (what is this Duplicate method name&signature ?).

**Comment by mavinkurve** [comment]
We started noticing this issue in version 3.9.0. It’s been working perfectly until the upgrade.

**Comment by joel-costigliola** [comment]
Moving to byte buddy seems to resolve this issue #1093 but this comes with other challenges.

**Comment by PascalSchumacher** [comment]
Could be the same issue as https://stackoverflow.com/questions/39670735/classformaterror-duplicate-method-namesignature-from-enhancerbyspringcglib where Rafael Winterhalter says it is a cglib bug.

It could also be related to our shading of cglib, see https://github.com/jdbi/jdbi/issues/26 for a similar issue.

@mavinkurve Which version were you using before upgrading to 3.9.0?

**Comment by mavinkurve** [comment]
We were using 3.8.0 and I confirmed by downgrading that this issue doesn’t
repo there.

**Comment by PascalSchumacher** [comment]
The exceptions occurs in `AbstractObjectArrayAssert`. Sadly a lot of methods have been added to `AbstractObjectArrayAssert` between `3.8.0` and `3.9.0` :(.

**Comment by joel-costigliola** [comment]
We are moving to byte buddy so this one is going to be fixed.

**Comment by mavinkurve** [comment]
Thanks everyone.

**Comment by filiphr** [comment]
@joel-costigliola I think that with you merging #1093 this one is resolved.
