### ISSUE TITLE
3.9.0 -> 3.9.1 upgrade on Java 8: Custom SoftAssertion implementation fails with Byte Buddy "java.lang.IllegalArgumentException: Could not create type"

### ISSUE THREAD

**Issue by mkobit** [joel-costigliola/assertj-core#1192]
#### Summary

I have a custom library that implements a custom `SoftAssertion` implementation that seems to fail on Java 8.

#### Example

* Test at https://github.com/mkobit/gradle-assertions/blob/b0e057007871b75fb37538bb423089f208b818fd/assertj-gradle/src/test/kotlin/com/mkobit/gradle/test/assertj/GradleSoftAssertionsTest.kt#L11 that can be ran with `./gradlew build`
    ```
    java.lang.IllegalArgumentException: Could not create type
    	at org.assertj.core.internal.bytebuddy.TypeCache.findOrInsert(TypeCache.java:140)
    	at org.assertj.core.internal.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:346)
    	at org.assertj.core.api.SoftProxies.create(SoftProxies.java:49)
    	at org.assertj.core.api.AbstractSoftAssertions.proxy(AbstractSoftAssertions.java:31)
    	at com.mkobit.gradle.test.assertj.GradleSoftAssertions.assertThat(GradleSoftAssertions.java:22)
    	at com.mkobit.gradle.test.assertj.GradleSoftAssertionsTest$can use soft assertions with BuildResult$1.call(GradleSoftAssertionsTest.kt:30)
    	at org.assertj.core.api.ThrowableAssert.catchThrowable(ThrowableAssert.java:62)
    	at org.assertj.core.api.AssertionsForClassTypes.catchThrowable(AssertionsForClassTypes.java:763)
    	at org.assertj.core.api.AssertionsForClassTypes.assertThatCode(AssertionsForClassTypes.java:734)
    	at org.assertj.core.api.Assertions.assertThatCode(Assertions.java:1169)
    	at com.mkobit.gradle.test.assertj.GradleSoftAssertionsTest.can use soft assertions with BuildResult$assertj_gradle(GradleSoftAssertionsTest.kt:29)
    ```

* https://github.com/mkobit/gradle-assertions/blob/b0e057007871b75fb37538bb423089f208b818fd/buildSrc/src/main/kotlin/buildsrc/DependencyInfo.kt#L19 can change between `3.9.0` and `3.9.1` to see difference

------

Java runtime	Oracle Java(TM) SE Runtime Environment 1.8.0_161-b12
Java 8 failing Gradle build scan: https://scans.gradle.com/s/bxs3savgndkou
Java 9 succeeding build scan: https://scans.gradle.com/s/ttdbpb4et4weu

**Comment by joel-costigliola** [comment]
Wow, that is weird, I'll give it a try on java 8 this week, I had a quick look at the code and it looks fine to me.

**Comment by joel-costigliola** [comment]
@mkobit  can you give a try to the latest master build ? there has been lot of improvements and fixes around soft assertions, it is worth giving it a try.

**Comment by mkobit** [comment]
Just built the same commit above against `7f33ba7d7a` of `assertj-core` using Jitpack, and the tests above succeeded :heavy_check_mark:

**Comment by joel-costigliola** [comment]
Sweet, closing the issue then
