### ISSUE TITLE
SoftAssertions' StringAssert fails with uninformative message when actual value contains two percent characters

### ISSUE THREAD

**Issue by patrick-albinson** [joel-costigliola/assertj-core#1209]
#### Summary

SoftAssertions' StringAssert fails with uninformative message when actual value contains two percent characters. We noticed this problem when trying to upgrade from 1.7.1 to the latest version (3.9.1).

#### Example

```java
SoftAssertions softAssertions = new SoftAssertions();
softAssertions.assertThat("%%E").matches("fffff");
softAssertions.assertAll();
```
Running this code in a test method results in the following stack trace:

```
java.util.MissingFormatArgumentException: Format specifier '%E'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.assertj.core.util.Strings.formatIfArgs(Strings.java:91)
	at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:62)
	at org.assertj.core.api.SoftAssertionError.createMessage(SoftAssertionError.java:55)
	at org.assertj.core.api.SoftAssertionError.<init>(SoftAssertionError.java:37)
	at org.assertj.core.api.SoftAssertions.assertAll(SoftAssertions.java:155)
```

**Comment by joel-costigliola** [comment]
It's a bug, we are using `String.format` without escaping `%`
