### ISSUE TITLE
ByteArrayAssert should provide the specific implementation for isEquals/containsExactly

### ISSUE THREAD

**Issue by luengnat** [joel-costigliola/assertj-core#1270]
#### Summary
ByteArrayAssert currently simply calls StandardComparisonStrategy.areEqual where it can be very slow to compare large byte array.

#### Example
The slowest part is Array.get call.
```java
	at java.lang.reflect.Array.get(Native Method)
	at org.assertj.core.util.Objects.areEqualArrays(Objects.java:59)
	at org.assertj.core.util.Objects.areEqual(Objects.java:44)
	at org.assertj.core.internal.StandardComparisonStrategy.areEqual(StandardComparisonStrategy.java:75)
	at org.assertj.core.internal.Objects.areEqual(Objects.java:348)
	at org.assertj.core.internal.Objects.assertEqual(Objects.java:319)
	at org.assertj.core.api.AbstractByteArrayAssert.containsExactly(AbstractByteArrayAssert.java:662)
```

**Comment by ardmn** [comment]
Hello @luengnat . I think it works same as ```containsExactly``` for int array or same as calling to ```arrays. assertContainsExactly()``` . Have you any proposals ? :)

**Comment by luengnat** [comment]
@ardmn it's just a performance issue where Array.get() is a reflection call into native call which can be quite slow as it involves boxing

**Comment by ardmn** [comment]
@luengnat if performance is critical for you can override assertion's methods . It is not nice but it works. Unfortunately, current assertj's api  does not provide the possibility to change/put/insert custom implementation for asserting . I mean that user can't use org.assertj.core.api.Assertions with custom org.assertj.core.api.ByteArrayAssert.

```java
import org.assertj.core.api.AbstractByteArrayAssert;
import org.assertj.core.api.ByteArrayAssert;
import org.assertj.core.internal.AbstractComparisonStrategy;
import org.assertj.core.internal.Failures;
import org.assertj.core.internal.StandardComparisonStrategy;
import org.junit.Test;

import java.util.Arrays;

import static org.assertj.core.error.ShouldBeEqual.shouldBeEqual;

public class MyByteArrayAssertTest {

    @Test
    public void test_isEqualTo_true() {
        MyByteArrayAssert.assertThat(new byte[]{1, 2, 3})
                .isEqualTo(new byte[]{1, 2, 3});
    }

    @Test
    public void test_isEqualTo_false() {
        MyByteArrayAssert.assertThat(new byte[]{1, 2, 3})
                .isEqualTo(new byte[]{1, 2, 3, 5, 6, 7, 8});
    }

    public static class MyByteArrayAssert extends ByteArrayAssert {

        private final Failures failures = Failures.instance();
        private final AbstractComparisonStrategy comparisonStrategy = StandardComparisonStrategy.instance();

        public MyByteArrayAssert(byte[] actual) {
            super(actual);
        }

        @Override
        public ByteArrayAssert isEqualTo(Object expected) {
            if (expected instanceof byte[]) {
                if (Arrays.equals(actual, (byte[]) expected)) {
                    return myself;
                }
                throw failures.failure(info, shouldBeEqual(actual, expected, comparisonStrategy, info.representation()));
            } else {
                return super.isEqualTo(expected);
            }
        }

        public static AbstractByteArrayAssert<?> assertThat(final byte[] actual) {
            return new MyByteArrayAssert(actual);
        }
    }
}


```

**Comment by luengnat** [comment]
@joel-costigliola do we need to preserve the binary compatibility down in the stack? Otherwise, I would prefer that we have a strongly typed org.assertj.core.util.Objects for each primitive and it will eliminate this performance problem.

**Comment by joel-costigliola** [comment]
The reason why there is no specific primitive array implementation was to avoid code duplication and reduce maintenance burden.

If someone wants to contribute a specific primitive array implementation, I think I'll be ok with that but I don't have the time to do it.

AssertJ tries to be as backward compatible as possible but if we need to break for good reasons, we do as long as it is relatively minor and adds more value than trouble.

**Comment by PascalSchumacher** [comment]
Implementing a new array/iterable assertion already requires massive effort. If we also add primitive array implementations this will increase the effort significantly. Therefore I think we should not do it.

For reference here is what it took to add `containsExactlyInAnyOrder`:
https://github.com/joel-costigliola/assertj-core/commit/bdd84ea99f78ab98528bdbd9078ea694f8d63c67 
https://github.com/joel-costigliola/assertj-core/commit/9ad596a4ba7883d2caf8d0bc8baa172ef86b653a

(Note that nowadays more effort would be required because `AtomicReferenceArray` support was added in the meantime.)

**Comment by luengnat** [comment]
@joel-costigliola I think it can be done without much change. All you need is a type specific implementation of Objects class and we can make it into a singleton instance for each type of Abstract*ArrayAssert. The interface should stay the same I think.

**Comment by joel-costigliola** [comment]
@luengnat I agree the production code change is not to big but you are forgetting the tests, it is massive to duplicate the tests done in the generic arrays implementation to validate the now specific one.

**Comment by luengnat** [comment]
I don't think you need to duplicate the test. We just need to inherit from https://github.com/joel-costigliola/assertj-core/blob/7ec117dd4083c83926ae3d5caa9a2c28d2cfb4b0/src/main/java/org/assertj/core/internal/ObjectArrays.java for each primitive type.

**Comment by joel-costigliola** [comment]
@luengnat not sure what you mean but happy to be proven wrong, keen for a PR?

**Comment by masterav10** [comment]
Many of my test cases use imagery (large byte arrays), so I've encountered this issues as well. I took at stab at fixing this. Turns out this is more complicated than it looks. There are a number of performance issues. For example, in the Arrays class you linked:
- Extensive use of ArrayList + IterableDiff results in massive performance problems due to Iterator.remove() causing a resize on large arrays.
- Arrays.get() is inefficient for large arrays due to memory generation (internally, it does not use Integer.valueOf, for instance).

I agree with Joel; I don't see a way to implement this without custom installation for each method. That said, most of the implementations would be identical per primitive type. 

Ideally, we should use code generation to reduce writing multiple implementations. A library like JavaPoet would be useful here.

**Comment by joel-costigliola** [comment]
Sorry for the late reply, I agree the implementation can be made more performant, thanks for looking into it.
