### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by joel-costigliola** [joel-costigliola/assertj-core#1338]
#### Summary

https://travis-ci.org/joel-costigliola/assertj-core/jobs/438379689
```
ERROR] Errors: 
[ERROR]   ObjectArrayAssert_extractingResultOf_Test.extractingResultOf_should_keep_assertion_state:115 » Introspection
[ERROR]   ObjectArrayAssert_extractingResultOf_Test.strongly_typed_extractingResultOf_should_keep_assertion_state:139 » Introspection
[ERROR]   ObjectArrayAssert_extracting_Test.extracting_by_multiple_names_should_keep_assertion_state:402 » Introspection
[ERROR]   ObjectArrayAssert_extracting_Test.extracting_by_name_should_keep_assertion_state:356 » Introspection
[ERROR]   ObjectArrayAssert_extracting_Test.extracting_by_several_functions_should_keep_assertion_state:333 » Introspection
[ERROR]   ObjectArrayAssert_extracting_Test.extracting_by_single_extractor_should_keep_assertion_state:425 » Introspection
[ERROR]   ObjectArrayAssert_extracting_Test.extracting_by_strongly_typed_name_should_keep_assertion_state:379 » Introspection
[ERROR]   ObjectArrayAssert_extracting_Test.extracting_by_throwing_extractor_should_keep_assertion_state:448 » Introspection
[INFO] 
```
All the errors above comes from this one:
```
[ERROR] extracting_by_name_should_keep_assertion_state  Time elapsed: 0.002 s  <<< ERROR!
org.assertj.core.util.introspection.IntrospectionError: 

Can't find any field or property with name 'comparatorsByType'.
Error when introspecting properties was :
- No public getter for property 'comparatorsByType' in org.assertj.core.api.ListAssert 
Error when introspecting fields was :
- Unable to obtain the value of the field <'comparatorsByType'> from <org.assertj.core.api.ListAssert@1>, check that field is public.
	at org.assertj.core.api.objectarray.ObjectArrayAssert_extracting_Test.extracting_by_name_should_keep_assertion_state(ObjectArrayAssert_extracting_Test.java:356)
Caused by: org.assertj.core.util.introspection.IntrospectionError: Unable to obtain the value of the field <'comparatorsByType'> from <org.assertj.core.api.ListAssert@1>, check that field is public.
	at org.assertj.core.api.objectarray.ObjectArrayAssert_extracting_Test.extracting_by_name_should_keep_assertion_state(ObjectArrayAssert_extracting_Test.java:356)
Caused by: java.lang.IllegalAccessException: can not accesscomparatorsByType because it is not public
	at org.assertj.core.api.objectarray.ObjectArrayAssert_extracting_Test.extracting_by_name_should_keep_assertion_state(ObjectArrayAssert_extracting_Test.java:356)
```

is it due to Travis bumping JDK version ?
```
java version "1.8.0_181"
```

**Comment by PascalSchumacher** [comment]
I do not think it is related to the java 8 version, because the build fails on every java version (9, 10, 11).

I guess the order in which tests are executed is different on travis and some test before the failing tests disables accessing private fields.

**Comment by PascalSchumacher** [comment]
fixed by https://github.com/joel-costigliola/assertj-core/commit/905cfdeeb9b01f35bab76377792eaca121146835

**Comment by joel-costigliola** [comment]
Good catch @PascalSchumacher, many thanks !
