### ISSUE TITLE
java.lang.IllegalArgumentException: Could not create type

### ISSUE THREAD

**Issue by jedpop** [joel-costigliola/assertj-core#1484]
I can successfully get soft assertions to work when running in debug mode using JavaSE-11 in Eclipse IDE for Java Developers, Version: 2019-03 (4.11.0), Build id: 20190314-1200
on Windows 10 64 bit but there's an error when I execute it in run mode:

"java.lang.IllegalArgumentException: Could not create type"

I'm using assertj-core-3.12.2.jar from the Maven repository.

Here's the simple test code:

package TestCasePack;

import org.assertj.core.api.SoftAssertionError;
import org.assertj.core.api.SoftAssertions;

public class tempMain {
	public static String tempstring = "whatshappening";
	
	public static void main(String[] args) {
		SoftAssertions softly = new SoftAssertions();
		
		try
		{
		softly.assertThat(tempstring).isEqualTo("whatshappening");
		softly.assertThat(tempstring).isEqualTo("whatsohappening");
		softly.assertThat(tempstring).isEqualTo("whatsoohappening");
		
		softly.assertAll();
		
		System.out.println(tempstring);
		}
		catch (SoftAssertionError e)
		{
			System.out.println(e.toString() );
		}
		catch (Exception e)
		{
			System.out.println(e.toString() );
		}
		finally
		{
			System.out.println();
		}
	}
}

When it's run in debug mode with no break points then there are two soft assertions listed (as expected) and all is well.

Here's the full exception after running:
Exception in thread "main" java.lang.IllegalArgumentException: Could not create type
	at org.assertj.core@3.12.2/org.assertj.core.internal.bytebuddy.TypeCache.findOrInsert(TypeCache.java:154)
	at org.assertj.core@3.12.2/org.assertj.core.internal.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:365)
	at org.assertj.core@3.12.2/org.assertj.core.api.SoftProxies.createSoftAssertionProxyClass(SoftProxies.java:118)
	at org.assertj.core@3.12.2/org.assertj.core.api.SoftProxies.createSoftAssertionProxy(SoftProxies.java:104)
	at org.assertj.core@3.12.2/org.assertj.core.api.AbstractSoftAssertions.proxy(AbstractSoftAssertions.java:31)
	at org.assertj.core@3.12.2/org.assertj.core.api.Java6AbstractStandardSoftAssertions.assertThat(Java6AbstractStandardSoftAssertions.java:485)
	at <redacted by jedpop>.tempMain.main(tempMain.java:15)
Caused by: java.lang.NoClassDefFoundError: java/lang/instrument/Instrumentation
	at org.assertj.core@3.12.2/org.assertj.core.internal.bytebuddy.utility.JavaModule$Dispatcher$CreationAction.run(JavaModule.java:270)
	at org.assertj.core@3.12.2/org.assertj.core.internal.bytebuddy.utility.JavaModule$Dispatcher$CreationAction.run(JavaModule.java:251)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.assertj.core@3.12.2/org.assertj.core.internal.bytebuddy.utility.JavaModule.<clinit>(JavaModule.java:45)
	at org.assertj.core@3.12.2/org.assertj.core.internal.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:454)
	at org.assertj.core@3.12.2/org.assertj.core.internal.bytebuddy.dynamic.loading.ClassInjector$UsingReflection$Dispatcher$CreationAction.run(ClassInjector.java:441)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.assertj.core@3.12.2/org.assertj.core.internal.bytebuddy.dynamic.loading.ClassInjector$UsingReflection.<clinit>(ClassInjector.java:130)
	at org.assertj.core@3.12.2/org.assertj.core.api.ClassLoadingStrategyFactory.classLoadingStrategy(ClassLoadingStrategyFactory.java:37)
	at org.assertj.core@3.12.2/org.assertj.core.api.SoftProxies.generateProxyClass(SoftProxies.java:178)
	at org.assertj.core@3.12.2/org.assertj.core.api.SoftProxies.lambda$createSoftAssertionProxyClass$0(SoftProxies.java:118)
	at org.assertj.core@3.12.2/org.assertj.core.internal.bytebuddy.TypeCache.findOrInsert(TypeCache.java:152)
	... 6 more
Caused by: java.lang.ClassNotFoundException: java.lang.instrument.Instrumentation
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 18 more

**Comment by joel-costigliola** [comment]
It is likely a classpath issue, can you check that `java.lang.instrument.Instrumentation` is available in your JRE ? I can find it in rt.jar in my environment.

**Comment by jedpop** [comment]
Thank you!

It's showing in my JRE:
![image](https://user-images.githubusercontent.com/23005828/55531399-c7812900-566f-11e9-94ad-d5ee39323313.png)

The CLASSPATH environment variable on my PC is set to the corresponding location for JDK library location.

**Comment by joel-costigliola** [comment]
I have tried your code with both java 8 and 11 and it ran with this ouput:

```
Exception in thread "main" org.opentest4j.MultipleFailuresError: Multiple Failures (2 failures)
	
Expecting:
 <"whatshappening">
to be equal to:
 <"whatsohappening">
but was not.
	
Expecting:
 <"whatshappening">
to be equal to:
 <"whatsoohappening">
but was not.
```

My environment is not exactly the same as yours as I was executing the test on Ubuntu and eclipse 20181214-0600.

Can you check the actual JRE used to run the program ? You can access that information in eclipse > Run > Run configurations... and then select the launched application and check the JRE tab (look also at the Dependencies tab) as in this screenshot:

![Selection_014](https://user-images.githubusercontent.com/382613/55548354-c3b4db80-572f-11e9-8aac-9adaa0badf84.png)

**Comment by jedpop** [comment]
I recreated the (very simple) project in Eclipse 20181214-0600 and have the same results when I run it from Eclipse.

Oddly, if I run it using Coverage it executes fine (just like in Debug).  First I have snapshots of the info you requested and later I created a runnable Jar and noticed some warnings due to illegal reflective access operations.

Here's the JRE used to run the program:
![image](https://user-images.githubusercontent.com/23005828/55665815-2af38e00-580b-11e9-9b21-753b89aa8b82.png)

Here's the Dependencies tab:
![image](https://user-images.githubusercontent.com/23005828/55665823-4bbbe380-580b-11e9-9a4f-f7010b21d633.png)

I created a runnable Jar and it successfully runs from command prompt; however, I see the following:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.assertj.core.api.AbstractSoftAssertions (file:/C:/Personal%20Folders/Jed/Eclipse%20Java%20Runnable%20Jars/testCase.jar) to field java.lang.Throwable.detailMessage
WARNING: Please consider reporting this to the maintainers of org.assertj.core.api.AbstractSoftAssertions
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
org.assertj.core.api.SoftAssertionError:
The following 2 assertions failed:
1)
Expecting:
 <"whatshappening">
to be equal to:
 <"whatsohappening">
but was not.
at testCase.main(testCase.java:22)
2)
Expecting:
 <"whatshappening">
to be equal to:
 <"whatsoohappening">
but was not.
at testCase.main(testCase.java:23)

**Comment by jedpop** [comment]
Hello,
I was able to get the soft asserts to work - I still get the warnings for "an illegal reflective access operation has occurred" but this issue can be closed.

Thanks for the suggestions.

I suspect there was a problem in the build path so here's a snapshot of my Build Path, Libraries:
![image](https://user-images.githubusercontent.com/23005828/56100178-2306ae80-5edb-11e9-8031-380c995de327.png)

Here's the Run Time JRE snapshot:
![image](https://user-images.githubusercontent.com/23005828/56100259-146cc700-5edc-11e9-9ef2-5ed42ea03d99.png)
