### ISSUE TITLE
AbstractThrowableAssert#isInstanceOf() throws IllegalAccessError

### ISSUE THREAD

**Issue by leadpony** [joel-costigliola/assertj-core#1656]
#### Summary

`AbstractThrowableAssert#isInstanceOf()` throws an `IllegalAccessError` exception 
when assertj-core is used as a modular jar. 

#### Example

```java
Throwable thrown = new IllegalArgumentException();
assertThat(thrown).isInstanceOf(NullPointerException.class);
```
Building and runing this example with JDK 9 or higher:
```bash
mvn package
java -p target/modules -m example/example.Example
```
outputs the following error messages:
```
Exception in thread "main" java.lang.IllegalAccessError: class org.assertj.core.util.Closeables (in module org.assertj.core) cannot access class java.util.logging.Logger (in module java.logging) because module org.assertj.core does not read module java.logging
	at org.assertj.core@3.14.0-SNAPSHOT/org.assertj.core.util.Closeables.<clinit>(Closeables.java:25)
	at org.assertj.core@3.14.0-SNAPSHOT/org.assertj.core.util.Throwables.getStackTrace(Throwables.java:172)
	at org.assertj.core@3.14.0-SNAPSHOT/org.assertj.core.error.ShouldBeInstance.<init>(ShouldBeInstance.java:67)
	at org.assertj.core@3.14.0-SNAPSHOT/org.assertj.core.error.ShouldBeInstance.shouldBeInstance(ShouldBeInstance.java:34)
	at org.assertj.core@3.14.0-SNAPSHOT/org.assertj.core.internal.Objects.assertIsInstanceOf(Objects.java:136)
	at org.assertj.core@3.14.0-SNAPSHOT/org.assertj.core.api.AbstractAssert.isInstanceOf(AbstractAssert.java:382)
	at example@1.0.0-SNAPSHOT/example.Example.main(Example.java:9)
```
The problem happens because `org.assertj.core.util.Closeables` requires `java.logging` module both at compile-time and at runtime.
Adding the following line to `src/main/java9/module-info.java` in asssertj-core repository will resolve the problem.
```java
requires java.logging;
```
Please find the attached project which reproduces the problem.
[assertj-example.zip](https://github.com/joel-costigliola/assertj-core/files/3775868/assertj-example.zip)

Thank you.

**Comment by joel-costigliola** [comment]
Thanks for reporting this @leadpony!

**Comment by scordio** [comment]
I am not very familiar with Java 9+ modules, but at first look it seems we don't have any [module-path testing](https://sormuras.github.io/blog/2018-09-11-testing-in-the-modular-world.html).

I would be happy to work on introducing that as it could allow us to have test cases like the one mentioned in this issue.

**Comment by joel-costigliola** [comment]
we did some manual testing with @sormuras but having a an automated test would be much better.

**Comment by leadpony** [comment]
Many open source projects compile *.java files TWICE in the release build.

1. First, compiles all files including `module-info.java` with  `--release 9`
2. Second, compiles all files excluding `module-info.java` with  `--release 8`

The final jar file contains `module-info.class` for Java 9 and all other *.class files for Java 8.

First compilation reports errors when `module-info.java` is incomplete to build all other *.java files.
I believe what compilers can do should be done by compilers.

**Comment by sormuras** [comment]
> I believe what compilers can do should be done by compilers.

Exactly.

As I stumbled over another issue, namely `requires java.instrument;` seems to be a special snow flake, I'll try to provide either an automated integration test or a better compile strategy that chokes on missing require statements. Or both... ;-)
