### ISSUE TITLE
Updating from 3.11.1 to 3.14.0 breaks

### ISSUE THREAD

**Issue by SElab2019** [joel-costigliola/assertj-core#1751]
When I try to upgrade assertj-core from 3.11.1 to the latest version 3.14.0. The following code breaks.
```
import static org.assertj.core.api.Assertions.assertThat;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

import org.junit.Test;

public class Testassertj {

    @Test
    public void demo() {
        
        Map<Path, String> test = new HashMap<Path, String>();
        Path path = Paths.get("/tmp/test/file");
        test.put(path, "69bf414bf3c9e4a1f9b08bc1bdfbf758b2deb65225eed120e4ff80a065099bd3cfee2f8b815fa2e64206eb447fbd1690a3d196f344852df68f3d45dc820a2cad");
        assertThat(test)
        .containsOnlyKeys(path)
        .containsValue("69bf414bf3c9e4a1f9b08bc1bdfbf758b2deb65225eed120e4ff80a065099bd3cfee2f8b815fa2e64206eb447fbd1690a3d196f344852df68f3d45dc820a2cad");
    }
}
```

The test should pass, but it failed with error:
```
Testassertj
demo(Testassertj)
java.lang.AssertionError: 
Expecting:
  <{/tmp/test/file="69bf414bf3c9e4a1f9b08bc1bdfbf758b2deb65225eed120e4ff80a065099bd3cfee2f8b815fa2e64206eb447fbd1690a3d196f344852df68f3d45dc820a2cad"}>
to contain only following keys:
  <[tmp, test, file]>
keys not found:
  <[tmp, test, file]>
and keys not expected:
  <[/tmp/test/file]>

	at Testassertj.demo(Testassertj.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this, we will look at it shortly.

**Comment by joel-costigliola** [comment]
The (subtle) issue is the addition of `containsOnlyKeys(Iterable<? extends K> keys)` in 3.12.0, it turns out to be a breaking change when given a `Path`, as `Path` is an `Iterable` the new method is called which check the elements (`tmp, test, file`) instead of the given `Path` itself.

In this case the best way forward is not to use `containsOnlyKeys` but a combination of `hasSize` chained with `containsKeys` (which does not have an overload with Iterable<? extends K> keys).

There is no way to fix this issue, except by removing the assertion but I'm not sure we should do that since it can be useful for "real" iterables.
At minimum, we will document the breaking change and add a warning in the javadoc.

**Comment by scordio** [comment]
What if we change `containsOnlyKeys(Iterable<? extends K> keys)` to:

```java
  public SELF containsOnlyKeys(Iterable<? extends K> keys) {
    if (keys instanceof Path) {
      K path = (K) keys;
      maps.assertContainsOnlyKeys(info, actual, path); // assertContainsOnlyKeys(AssertionInfo, Map<K, V>, K...)
    } else {
      maps.assertContainsOnlyKeys(info, actual, keys); // assertContainsOnlyKeys(AssertionInfo, Map<K, V>, Iterable<? extends K>)
    }
    return myself;
  }
```

This would mean you cannot use a `Path` as an `Iterable` anymore, but probably this is not a real use case.

**Comment by joel-costigliola** [comment]
Good thinking @scordio!

**Comment by SElab2019** [comment]
Thanks for your helping and confirmation!
