### ISSUE TITLE
NPE in DualValue.isPotentialCyclingValue while using recursive comparison

### ISSUE THREAD

**Issue by epeee** [joel-costigliola/assertj-core#1866]
#### Summary

```
java.lang.NullPointerException
	at org.assertj.core.api.recursive.comparison.DualValue.isPotentialCyclingValue(DualValue.java:225)
	at org.assertj.core.api.recursive.comparison.DualValue.hasPotentialCyclingValues(DualValue.java:218)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator$ComparisonState.pickDualValueToCompare(RecursiveComparisonDifferenceCalculator.java:100)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator.determineDifferences(RecursiveComparisonDifferenceCalculator.java:200)
	at org.assertj.core.api.recursive.comparison.RecursiveComparisonDifferenceCalculator.determineDifferences(RecursiveComparisonDifferenceCalculator.java:188)
	at org.assertj.core.api.RecursiveComparisonAssert.determineDifferencesWith(RecursiveComparisonAssert.java:970)
	at org.assertj.core.api.RecursiveComparisonAssert.isEqualTo(RecursiveComparisonAssert.java:159)
```

It looks like we should check if `java.lang.Class#getCanonicalName` is `null` as well. According to the java doc this can be the case, see [javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html#getCanonicalName--).

https://github.com/joel-costigliola/assertj-core/blob/a64f3fb4e942d85a671fedc98eca3d8e262772ff/src/main/java/org/assertj/core/api/recursive/comparison/DualValue.java#L221-L226

I will add a sample later on.

#### Example

```java
<add example here>
```

**Comment by joel-costigliola** [comment]
good catch, my bad!

**Comment by epeee** [comment]
yep, a bugfix release would be great.

thx!

**Comment by joel-costigliola** [comment]
I'm curious if you experienced the error from a real test case.
I have added the test for local classes but not yet anonymous ones, it feels a bit of an edge case but that needs to be fixed anyway

**Comment by epeee** [comment]
Yes, it is from a real test.

a sample to reproduce it might be

```java
  enum TEST {
    A1 {
      @Override
      boolean test() {
        return false;
      }
    };

    abstract boolean test();
  }

  class C {
    TEST t = TEST.A1;
  }

  @Test
  public void testB() {
    C actual = new C();
    C expected = new C();

    assertThat(actual).usingRecursiveComparison().isEqualTo(expected);
  }
```

I will have a look at the other test cases failing due to this one later on, most likely I can share another example later on today.

**Comment by joel-costigliola** [comment]
@epeee I have created https://github.com/joel-costigliola/assertj-core/pull/1868 to fix this issue and added you as a reviewer.
Feel free to push more commits if you find more test to add.

**Comment by epeee** [comment]
@joel-costigliola thx!
I was able to track all the failing test cases down to the samples you already added in the newly added test case.

**Comment by joel-costigliola** [comment]
3.16.1 released, should be available in a few hours in maven central

**Comment by epeee** [comment]
works like a charm.
thx for the fast turnaround!
