### ISSUE TITLE
OOM during StringBuilder in AssertionErrorMessagesAggregrator#aggregrateErrorMessages

### ISSUE THREAD

**Issue by fivetran-andydreyfuss** [joel-costigliola/assertj-core#1908]
#### Summary
Building the string for an assertAll can lead to an OOM, it would be better to return a truncated message if the error count is larger than some configurable number - or at least defensively check of catch OOM and produce a more useful outcome than

```
Java heap space
java.lang.OutOfMemoryError: 
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at org.assertj.core.error.AssertionErrorMessagesAggregrator.aggregrateErrorMessages(AssertionErrorMessagesAggregrator.java:25)
	at org.assertj.core.api.SoftAssertionError.<init>(SoftAssertionError.java:36)
	at org.assertj.core.error.AssertionErrorCreator.multipleSoftAssertionsError(AssertionErrorCreator.java:75)
	at org.assertj.core.api.SoftAssertions.assertAll(SoftAssertions.java:166)
	at com.redacted.testThing(Redacted.java:129)
```

This should be easy to repro.

Thanks for considering - I can submit a PR if that would help here.

**Comment by joel-costigliola** [comment]
We should definitely avoid OOM, just curious how many errors you had to get there.
Contribution appreciated, we already have a mechanism to limit the output when displaying iterable or array.

**Comment by fivetran-andydreyfuss** [comment]
lol ... a lot I guess, no way to know 🤷 

Would you mind pointing me to the docs on how to configure that, or just describing how you would go find it and I can figure it out?

Thanks kindly!

**Comment by joel-costigliola** [comment]
fair enough :) that should have been a lot assertions going on.

have a look at the configuration class and add a field for you ruse case, https://github.com/joel-costigliola/assertj-core/blob/bb18e16e10c3dcce7bd32b0e69efdaa99690b2a2/src/main/java/org/assertj/core/configuration/Configuration.java#L56 then you would have to update the `AssertionErrorMessagesAggregrator` to limit the number of errors displayed, another option to consider would to limit the number of collected errors which happens in SoftProxies.

**Comment by fivetran-andydreyfuss** [comment]
Right on thanks Joel, and thanks for making this library as well as all the extensions, cool stuff.
