### ISSUE TITLE
Extracting on JsonNode sends child node to extractor, not root

### ISSUE THREAD

**Issue by davidmichaelkarr** [joel-costigliola/assertj-core#1954]
The problem can be demonstrated with this simple test class:
```package jsonexperiments;

import static org.assertj.core.api.Assertions.*;

import org.junit.Test;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;

public class JSONStuffTest {
    @Test
    public void jsonExtractingProblem() throws Exception {
        String    jsonString  = "{\"content\":{\"enterpriseType\":\"abc\"}}";

        ObjectMapper    objectMapper    = new ObjectMapper();
        JsonNode  jsonNode    = objectMapper.readTree(jsonString);
        System.out.println("jsonNode[" + jsonNode + "]");
        
        assertThat(jsonNode)
            .extracting(jn -> textAtPath(jn, "/content/enterpriseType"))
            .containsExactly("abc");
    }
    
    private String textAtPath(JsonNode node, String path) {
        System.out.println("node[" + node + "]");
        return node.at(path).asText();
    }
}
```
When this runs, it fails with the following stack trace:
```java.lang.AssertionError: 
Expecting:
  <[""]>
to contain exactly (and in same order):
  <["abc"]>
but some elements were not found:
  <["abc"]>
and others were not expected:
  <[""]>

	at jsonexperiments.JSONStuffTest.jsonExtractingProblem(JSONStuffTest.java:21)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

```
And the following stdout:
```jsonNode[{"content":{"enterpriseType":"abc"}}]
node[{"enterpriseType":"abc"}]
```
As you can see, the original content has a "content" node at the root, but the extractor receives the child of that node, not the root node. The assertion fails because it logically expects to find "/content/enterpriseType", but it does not, because "content" doesn't exist in what was passed to the extractor.

For completeness, here is the pom.xml:
```<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.att.example</groupId>
    <artifactId>jsonexperiments</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-databind</artifactId>
            <version>2.9.10</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.core</groupId>
            <artifactId>jackson-annotations</artifactId>
            <version>2.9.10</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-smile</artifactId>
            <version>2.9.10</version>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.dataformat</groupId>
            <artifactId>jackson-dataformat-yaml</artifactId>
            <version>2.9.10</version>
        </dependency>
        <dependency>
            <groupId>org.apache.commons</groupId>
            <artifactId>commons-lang3</artifactId>
            <version>3.5</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>3.16.1</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
</project>
```

**Comment by scordio** [comment]
`JsonNode` is an `Iterable`, therefore `extracting` is applied to all its elements. I guess the correct assertion would be:

```java
  assertThat(jsonNode)
    .extracting(jn -> textAtPath(jn, "/enterpriseType"))
    .containsExactly("abc");
```
To have a bit more of flexibility for JSON assertions, you might want to consider [JsonUnit](https://github.com/lukas-krecan/JsonUnit).

**Comment by joel-costigliola** [comment]
Another option would be to use `assertThatObject` which forces using object assertions.

**Comment by davidmichaelkarr** [comment]
Ok, well, that was completely nonintuitive.  Changing it to "assertThatObject" just makes it work, and it also allows me to perform multiple extractions and value assertions.

If I change it to
```
        String    jsonString  = "{\"content\":{\"enterpriseType\":\"abc\",\"businessType\":\"def\"}}";
        ...
        assertThatObject(jsonNode)
            .extracting(jn -> textAtPath(jn, "/content/enterpriseType"),
                        jn -> textAtPath(jn, "/content/businessType"))
            .containsExactly("abc", "def");
```
It works perfectly fine.

Although I can see the clear result of what happens when I use "assertThat" instead, which returns an "IterableAssert" in this case, I don't understand the implications of "therefore extracting is applied to all its elements".

I also don't quite understand what "but also no additional list assertions" means from the javadoc of "assertThatObject()".

**Comment by davidmichaelkarr** [comment]
Using JsonUnit, I verified that the following is equivalent:
```
        assertThatJson(jsonNode)
            .and(a -> a.node("content.enterpriseType").isEqualTo("abc"),
                 a -> a.node("content.businessType").isEqualTo("def"));
```

**Comment by joel-costigliola** [comment]
> I use "assertThat" instead, which returns an "IterableAssert" in this case, I don't understand the implications of "therefore extracting is applied to all its elements".

it means like a map operation on a [stream](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/util/stream/Stream.html), the extracting function is called for each elements and the result is another iterable with the extracted values, so if you have a list(e1, e2, e3) after extracting their hashCode you would have a list(e1.hashCode(), e2.hashCode(), e3.hashCode()). 

> Ok, well, that was completely nonintuitive

Agreed but not much we can do here, if a type is an iterable, `assertThat` will favor iterable over object as it is more specific.

> I also don't quite understand what "but also no additional list assertions" means from the javadoc of "assertThatObject()".

The example was showing a list, but since `assertThatObject()` returns object assertions, you won't have access to list assertions like `hasSize` or `contains`.
