### ISSUE TITLE
PredicateAssert accepts/rejects fails with single null parameter

### ISSUE THREAD

**Issue by scordio** [joel-costigliola/assertj-core#1969]
#### Summary

[assertj/doc#65] AbstractPredicateAssert.accepts and rejects throws on null value. This prevents testing if the Predicate correctly handles null values.

#### Example

```java
Predicate<Boolean> isTrue = v -> v == null ? false : v;
assertThat(isTrue).rejects(null); 
```

yields:

```java
java.lang.NullPointerException
	at org.assertj.core.api.AbstractPredicateAssert.rejects(AbstractPredicateAssert.java:88)
	at org.assertj.core.api.PredicateAssert.rejects(PredicateAssert.java:40)
```

**Comment by scordio** [comment]
@cameronbraid the problem is that `accepts` and `rejects` expect a vararg and a `null` value is ambiguous as it can refer to either a single element or to an array.

If you cast `null` to a `Boolean` then it should work:

```java
Predicate<Boolean> isTrue = v -> v == null ? false : v;
assertThat(isTrue).rejects((Boolean) null); 
```

Would this cover your use case?

**Comment by cameronbraid** [comment]
Hrm, yeah that's a sufficient workaround.

Though you may be able to code the rejects using two methods, the first will be called with a single arg when null

```
  public SELF rejects(@SuppressWarnings("unchecked") T value) {
     // allow null here
  }
  public SELF rejects(@SuppressWarnings("unchecked") T first, @SuppressWarnings("unchecked") T... rest) {
    // disabllow null here
  }
```

**Comment by scordio** [comment]
With the way you suggested it's no longer possible to provide only an array of values, so it would be a breaking change. Also, the internal implementation and assertion would become a bit more complex.

Still doable but I'm not sure if it's a reasonable price to pay to avoid casting the null value.

@joel-costigliola thoughts?

**Comment by joel-costigliola** [comment]
I agree with @scordio, I think it is sufficient to update the javadoc for this use case.

We could also add `rejectsNull`/`acceptsNull`, it feels a bit of work for a minor corner case though.
