### ISSUE TITLE
AssertJ Core 3.17.0 and AssertJ Swing 3.9.2 - NoSuchMethodError

### ISSUE THREAD

**Issue by tifhorn** [joel-costigliola/assertj-core#1974]
Hello.

I've upgraded today to newest Assertj Core and it seems to not work properly when using Assertj Swing at the same time, resulting in following stacktrace:

```java
java.lang.NoSuchMethodError: org.assertj.core.api.AbstractBooleanAssert.as(Lorg/assertj/core/description/Description;)Lorg/assertj/core/api/AbstractAssert;

	at org.assertj.swing.driver.ComponentDriver.requireFocused(ComponentDriver.java:246)
	at org.assertj.swing.fixture.AbstractComponentFixture.requireFocused(AbstractComponentFixture.java:353)
	at org.awaitility.core.AssertionCondition$1.eval(AssertionCondition.java:55)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:201)
	at org.awaitility.core.ConditionAwaiter$ConditionPoller.call(ConditionAwaiter.java:188)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

It's hard to tell exactly which line of my code causes it, but should it work together with Assertj Swing without problems or strange dependency manipulation? Or there's some additional step to make in order to get it to work?

**Comment by scordio** [comment]
It seems AssertJ Swing is still using assertj-core 3.11.1 and `Descriptable#as(Description)` became binary incompatible on 3.15.0 with 618609cc0a05414ef1a117cf616621310cd062ee.

Could you check if 3.14.0 works correctly?

**Comment by tifhorn** [comment]
@scordio  Thanks for Your reply. Yes indeed, 3.14.0 works correctly, while from 3.15+ it fails with above error.
Is there any plan of upgrading AssertJ Swing to newest AssertJ Core dependencies?

**Comment by scordio** [comment]
Yes, sure. I will follow up on this.

**Comment by joel-costigliola** [comment]
closing this as https://github.com/joel-costigliola/assertj-swing/issues/252 describes the same error.
