### ISSUE TITLE
[AssertJ core 1.7.1] IllegalFormatConversionException when failWithMessage with '%d' placeholder

### ISSUE THREAD

**Issue by fbiville** [joel-costigliola/assertj-core#320]
I've got the following assertion:

```java
   public ResponseAssert hasStatusCode(int code) {
      isNotNull();

      int actualStatus = actual.code();
      if (actualStatus != code) {
         failWithMessage("Expected HTTP status <%d>, got HTTP status <%d>", code, actualStatus);
      }
      return this;
   }
```

Which ends up failing like this:

```
java.util.IllegalFormatConversionException: d != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4045)
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2748)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2702)
	at java.util.Formatter.format(Formatter.java:2488)
	at java.util.Formatter.format(Formatter.java:2423)
	at java.lang.String.format(String.java:2790)
	at org.assertj.core.util.Strings.formatIfArgs(Strings.java:96)
	at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:63)
	at org.assertj.core.error.BasicErrorMessageFactory.create(BasicErrorMessageFactory.java:120)
	at org.assertj.core.internal.Failures.failure(Failures.java:97)
	at org.assertj.core.api.AbstractAssert.failWithMessage(AbstractAssert.java:107)
	at com.vidal.excalibur.service.resource.assertions.ResponseAssert.hasStatusCode(ResponseAssert.java:57)
```

As a workaround: `%s` instead of `%d` works as expected.

**Comment by joel-costigliola** [comment]
This is indeed a bug as it will use AssertJ formatter that convert each object to a String and then call `String#format` (this is the way AssertJ error messages are built), that will fail if you pass any other format specifier than `%s`.
We should be simpler and directly use `String#format` here.
