### ISSUE TITLE
Assertions with maps does not seem to work.

### ISSUE THREAD

**Issue by SMontgomery** [joel-costigliola/assertj-core#395]
I am probably doing something stupid.  But I can't seem to figure out what it is.

Whenever I try to do assertions on maps I get a NoSuchMethodError error.  I am running Java 8, AssertJ Core 3.0.0 and Junit 4.12.  All other assertions work fine.

```java
import java.util.HashMap;
import java.util.Map;
import org.assertj.core.api.Assertions;
import org.junit.Test;

public class MapTest {

    @Test
    public void mapTest() {
        Map<String, String> map = new HashMap<>();
        map.put("Key1", "Value1");
        map.put("Key2", "Value2");
        Assertions.assertThat(map).isNotNull();
    }
}
```

```
java.lang.NoSuchMethodError: org.assertj.core.api.Assertions.assertThat(Ljava/util/Map;)Lorg/assertj/core/api/MapAssert;
	at engine.api.MapTest.mapTest(MapTest.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:74)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:211)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:67)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by joel-costigliola** [comment]
I think it works on java 8, I have a project examples that runs a bunch of assertions including map ones, see [MapAssertionsExamples in java 8 branch](https://github.com/joel-costigliola/assertj-examples/blob/java-8/assertions-examples/src/test/java/org/assertj/examples/MapAssertionsExamples.java).

Having said that, I suspect a classpath pb, check that your dependencies resolve to assertj-core 3.0.
Using maven that would be `mvn depdendency:tree`

**Comment by SMontgomery** [comment]
Thanks for the response.  Looks like 3.0.0 is the only one there.  Just found out that it works when I drop to the console so it would appear my IDE is doing something odd.
