### ISSUE TITLE
DateAssert_with_string_based_date_representation_Test#date_assertion_should_support_timestamp_string_representation - flakey?

### ISSUE THREAD

**Issue by dorzey** [joel-costigliola/assertj-core#405]
When running this test through either maven or IntelliJ it fails about 1 in 10 times with the following error:
```
java.lang.AssertionError: 
Expecting:
 <"2015-05-07T14:52:18 (Date@2e6f0bab)">
to be equal to:
 <"2015-05-07T14:52:18 (Date@2e6f0952)">
but was not.
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:78)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)
```
Please find below of the differences for when a test fails:

Actual | Expected
--- | ---
2015-05-07T15:18:31.390+0200 | 2015-05-07T15:18:31.039+0200
2015-05-07T15:19:34.620+0200 | 2015-05-07T15:19:34.062+0200
2015-05-07T15:21:34.610+0200 | 2015-05-07T15:21:34.061+0200
2015-05-07T15:24:00.640+0200 | 2015-05-07T15:24:00.064+0200
2015-05-07T15:24:35.170+0200 | 2015-05-07T15:24:35.017+0200

There would appear to be a pattern in the differences.

I've created https://github.com/dorzey/assertj-core/tree/DateAssert_flakey to help others replicate the issues. This makes use of the `ReliabilityRule` in [co.unruly.junit-rules](https://github.com/unruly/junit-rules)

Has anybody else seen the same issue? Or can anybody else replicate it?

**Comment by joel-costigliola** [comment]
I can replicate it by executing the tests in a loop. I have different failure results though:
```
timestampAsString             : 2015-05-08 09:52:52.54
actual in TimestampDateFormat : 2015-05-08 09:52:52.540

timestampAsString             : 2015-05-08 09:53:30.86
actual in TimestampDateFormat : 2015-05-08 09:53:30.860
```
It always fail with that pattern, the time is the same but the representation is slightly different.

Not sure what the reason is though, I still need to investigate that.

**Comment by joel-costigliola** [comment]
It looks like this is a time representation precision problem .
Running that test will fail at some point:

```java
final DateFormat timestampFormat = Dates.newTimestampDateFormat();
for (int i = 0; i < 100; i++) {
	final Date date = new Date();
	final Timestamp ts = new Timestamp(date.getTime());
	System.out.println("ts.toString()                                                : " 
			+ ts.toString());
	System.out.println("timestampFormat.format(timestampFormat.parse(ts.toString())) : "
			+ timestampFormat.format(timestampFormat.parse(ts.toString())));
	assertThat(date).isEqualTo(ts.toString());
}
```

Error occurs when the ms precision 2 digits instead of 3 :

```
timestampFormat.format(timestampFormat.parse(ts.toString())) : 2015-05-08 11:17:36.378
ts.toString()                                                : 2015-05-08 11:17:36.378
timestampFormat.format(timestampFormat.parse(ts.toString())) : 2015-05-08 11:17:36.378
ts.toString()                                                : 2015-05-08 11:17:36.378
timestampFormat.format(timestampFormat.parse(ts.toString())) : 2015-05-08 11:17:36.378
ts.toString()                                                : 2015-05-08 11:17:36.379
timestampFormat.format(timestampFormat.parse(ts.toString())) : 2015-05-08 11:17:36.379
ts.toString()                                                : 2015-05-08 11:17:36.379
timestampFormat.format(timestampFormat.parse(ts.toString())) : 2015-05-08 11:17:36.379
ts.toString()                                                : 2015-05-08 11:17:36.379
timestampFormat.format(timestampFormat.parse(ts.toString())) : 2015-05-08 11:17:36.379
ts.toString()                                                : 2015-05-08 11:17:36.38
timestampFormat.format(timestampFormat.parse(ts.toString())) : 2015-05-08 11:17:36.038
```

**Comment by joel-costigliola** [comment]
`DateAssert_with_string_based_date_representation_Test` is fixed if we replace: 
```java
String timestampAsString = timestamp.toString();
```
by
```java
String timestampAsString = Dates.newTimestampDateFormat().format(timestamp);
```
