### ISSUE TITLE
NoSuchMethodException when calling SoftAssertions#assertThat(Comparable)

### ISSUE THREAD

**Issue by lbilger** [joel-costigliola/assertj-core#688]
#### Summary
Using SoftAssertions to inspect a ```java.lang.Comparable``` fails with the following Exception:
```
org.assertj.core.internal.cglib.core.CodeGenerationException: java.lang.NoSuchMethodException-->org.assertj.core.api.AbstractComparableAssert$$EnhancerByCGLIB$$fea5c76c.<init>(java.lang.Comparable)

	at org.assertj.core.internal.cglib.core.ReflectUtils.getConstructor(ReflectUtils.java:255)
	at org.assertj.core.internal.cglib.core.ReflectUtils.newInstance(ReflectUtils.java:227)
	at org.assertj.core.internal.cglib.proxy.Enhancer.createUsingReflection(Enhancer.java:650)
	at org.assertj.core.internal.cglib.proxy.Enhancer.firstInstance(Enhancer.java:549)
	at org.assertj.core.internal.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:244)
	at org.assertj.core.internal.cglib.proxy.Enhancer.createHelper(Enhancer.java:378)
	at org.assertj.core.internal.cglib.proxy.Enhancer.create(Enhancer.java:305)
	at org.assertj.core.api.SoftProxies.create(SoftProxies.java:38)
	at org.assertj.core.api.AbstractSoftAssertions.proxy(AbstractSoftAssertions.java:26)
	at org.assertj.core.api.AbstractStandardSoftAssertions.assertThat(AbstractStandardSoftAssertions.java:166)
...
Caused by: java.lang.NoSuchMethodException: org.assertj.core.api.AbstractComparableAssert$$EnhancerByCGLIB$$fea5c76c.<init>(java.lang.Comparable)
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.getDeclaredConstructor(Class.java:2178)
	at org.assertj.core.internal.cglib.core.ReflectUtils.getConstructor(ReflectUtils.java:251)
	... 37 more
```

#### Example

```java
new SoftAssertions().assertThat((Comparable)null);
```

#### Java 8 specific ?
NO
* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

**Comment by PascalSchumacher** [comment]
This looks like https://github.com/joel-costigliola/assertj-core/issues/638

Are you using 3.4.0 or 2.4.0?

If yes, please update to 3.4.1 or 2.4.1.

**Comment by lbilger** [comment]
You're right, I was using 3.4.0 and wasn't aware there was a 3.4.1. With 3.4.1 it works.

**Comment by PascalSchumacher** [comment]
Glad to help. :)

**Comment by joel-costigliola** [comment]
@PascalSchumacher  :+1:
