### ISSUE TITLE
Do not print full collection/map when really big

### ISSUE THREAD

**Issue by sta-szek** [joel-costigliola/assertj-core#747]
#### Summary
AssertJ causes `Exception in thread "main" java.lang.OutOfMemoryError: Java heap space` when asserting that list hasSize.  List has 915705 elements which are combinations of class `H` with different fields values. Problem occues when assertion will fail

Classes:

```
    @Data
    class A {
        int a;
        int b;
    }

    @Data
    class B {
        int a;
        int b;
        int c;
    }

    @Data
    class C {
        int a;
        int b;
        int c;
        int d;
    }

    @Data
    class D {
        int a;
        E e;
        F f;
    }

    @Data
    class E {
        int b;
    }

    @Data
    class F {
        int d;
    }

    @Data
    class G {
        int d;
        F f;
    }

    @Data
    class H {
        A a;
        B b;
        C c;
        D d;
        E e;
        F f;
        G g;
    }
```
#### Example
The assertion below
![image](https://cloud.githubusercontent.com/assets/6240704/18022331/242cead2-6bee-11e6-9b6d-278b6bf42bcb.png)

will throw exception with following logs:

```
Connected to the target VM, address: '127.0.0.1:63061', transport: 'socket'
sie 27, 2016 12:33:08 AM org.junit.platform.launcher.core.ServiceLoaderTestEngineRegistry loadTestEngines
INFO: Discovered TestEngines with IDs: [junit-jupiter, junit-vintage]
Disconnected from the target VM, address: '127.0.0.1:63061', transport: 'socket'
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
	at java.lang.StringBuilder.append(StringBuilder.java:136)
	at java.lang.StringBuilder.append(StringBuilder.java:76)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:484)
	at java.lang.StringBuilder.append(StringBuilder.java:166)
	at java.lang.StringBuilder.append(StringBuilder.java:76)
	at java.util.Formatter$FixedString.print(Formatter.java:2595)
	at java.util.Formatter.format(Formatter.java:2508)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at org.assertj.core.util.Strings.formatIfArgs(Strings.java:91)
	at org.assertj.core.error.MessageFormatter.format(MessageFormatter.java:61)
	at org.assertj.core.error.BasicErrorMessageFactory.create(BasicErrorMessageFactory.java:110)
	at org.assertj.core.internal.Failures.failure(Failures.java:112)
	at org.assertj.core.internal.CommonValidations.checkSizes(CommonValidations.java:117)
	at org.assertj.core.internal.Iterables.assertHasSize(Iterables.java:173)
	at org.assertj.core.api.AbstractIterableAssert.hasSize(AbstractIterableAssert.java:136)
```

I put breakpoint in class `BasicErrorMessageFactory` and the debbuger view show `collecting data` as shown below.
![image](https://cloud.githubusercontent.com/assets/6240704/18022484/92fa1b5a-6bef-11e6-88af-3b5f632a83f5.png)

And after few seconds method `toString()` from `ShouldHaveSize` class threw exception `java.lang.OutOfMemoryError` as shown below
![image](https://cloud.githubusercontent.com/assets/6240704/18022540/048dae3a-6bf0-11e6-8928-67b3f15b7fef.png)

But this exception is caused by IntelliJ as it calls the `toString()` method when representing objects in debbuger view. Workaround for this is to set `View as` to `Object`

![image](https://cloud.githubusercontent.com/assets/6240704/18022664/1d18e8ec-6bf1-11e6-93d0-5c4479fe1d09.png)

I thkink problem is somewhere in `BasicErrorMessageFactory.create(...)` method or methods called by this one.

I suggest not to `print` large Collections (Lists, HashMaps, etc...)
This could be done intelligently, by getting some info form `Runtime.getRuntime().*Memory` and trying to decide whether collection is to big or not :laughing: 

#### Java 8 specific ?
* NO  : create Pull Request from the `2.x` branch

**Comment by joel-costigliola** [comment]
I think it makes sense not to print more than 1000 (?) elements (showing `...` to make it clear we haven't displayed the complete collection).

**Comment by sta-szek** [comment]
BTW consider not to print iterables, streams, arrays, etc.. just everything where is more than one object

**Comment by joel-costigliola** [comment]
That was part of the plan ! :)

**Comment by joel-costigliola** [comment]
Fixed.
