### ISSUE TITLE
Java6SoftAssertions failed for Android

### ISSUE THREAD

**Issue by ddhodapkar** [joel-costigliola/assertj-core#761]
#### Summary
Java6SoftAssertions failed for Android with java.lang.ExceptionInitializerError for version 2.5.0

java.lang.ExceptionInInitializerError
at org.assertj.core.api.SoftProxies.create(SoftProxies.java:34)
at org.assertj.core.api.AbstractSoftAssertions.proxy(AbstractSoftAssertions.java:28)
at org.assertj.core.api.Java6AbstractStandardSoftAssertions.assertThat(Java6AbstractStandardSoftAssertions.java:452)
at com.groupon.test.rc.tests.Java6AssertTest.testSoftAssertions(Java6AssertTest.java:48)

#### Example

In build.gradle of the android app

androidTestCompile 'org.assertj:assertj-core:2.5.0'

Use Java6SoftAssertions entry point

Example code:

@Test(timeout = Timeouts.TEST_TIMEOUT_NORMAL)
    public void testJava6Asserts() throws Exception {
        Java6SoftAssertion softAssert = new Java6SoftAssertion();
        String distanceFilter= InstrumentationRegistry.getTargetContext().getResources().getString(R.string.filters_sort_distance);
        softAssert.assertThat(distanceFilter).as("DistanceFilter value matches").isEqualTo("Distance");
}

Running the test fails - . 
java.lang.ExceptionInInitializerError
at org.assertj.core.api.SoftProxies.create(SoftProxies.java:34)
at org.assertj.core.api.AbstractSoftAssertions.proxy(AbstractSoftAssertions.java:28)
at org.assertj.core.api.Java6AbstractStandardSoftAssertions.assertThat(Java6AbstractStandardSoftAssertions.java:452)
at com.groupon.test.rc.tests.Java6AssertTest.testSoftAssertions(Java6AssertTest.java:48)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.lang.Thread.run(Thread.java:818)
Caused by: org.assertj.core.internal.cglib.core.CodeGenerationException: java.lang.reflect.InvocationTargetException-->null
at org.assertj.core.internal.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:237)
at org.assertj.core.internal.cglib.core.KeyFactory$Generator.create(KeyFactory.java:144)
at org.assertj.core.internal.cglib.core.KeyFactory.create(KeyFactory.java:116)
at org.assertj.core.internal.cglib.core.KeyFactory.create(KeyFactory.java:108)
at org.assertj.core.internal.cglib.core.KeyFactory.create(KeyFactory.java:104)
at org.assertj.core.internal.cglib.proxy.Enhancer.<clinit>(Enhancer.java:69)
... 14 more
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.assertj.core.internal.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:384)
at org.assertj.core.internal.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:219)
... 19 more
Caused by: java.lang.UnsupportedOperationException: can't load this type of class file
at java.lang.ClassLoader.defineClass(ClassLoader.java:300)
... 23 more

#### Java 8 specific ?

No
Java 7

**Comment by joel-costigliola** [comment]
it seems to be related to this : http://stackoverflow.com/questions/34843244/android-instrumentation-tests-with-mockito

**Comment by joel-costigliola** [comment]
I'm closing this issue as we don't actively support Android - we just try to and rely on the community to maintain it.
