### ISSUE TITLE
NPE in ShouldBeEqual.defaultDetailedErrorMessage() when actual or expected is null

### ISSUE THREAD

**Issue by Gubbel** [joel-costigliola/assertj-core#870]
#### Summary

The `ShouldBeEqual.detailedToStringOf(Object)` method cannot handle `null` objects. This issue occurs when comparing a `null` object with an object that returns `null` from its `toString()` method (see example).

```
java.lang.NullPointerException
	at org.assertj.core.error.ShouldBeEqual.detailedToStringOf(ShouldBeEqual.java:188)
	at org.assertj.core.error.ShouldBeEqual.detailedActual(ShouldBeEqual.java:193)
	at org.assertj.core.error.ShouldBeEqual.defaultDetailedErrorMessage(ShouldBeEqual.java:163)
	at org.assertj.core.error.ShouldBeEqual.newAssertionError(ShouldBeEqual.java:114)
	at org.assertj.core.internal.Failures.failure(Failures.java:91)
	at org.assertj.core.internal.Objects.assertEqual(Objects.java:321)
	at org.assertj.core.api.AbstractAssert.isEqualTo(AbstractAssert.java:213)
	at SampleTest.testIsEqualTo(SampleTest.java:16)
	...
```

I would expect an error message like
```
java.lang.AssertionError: 
Expecting:
 <null>
to be equal to:
 <"null (ToStringIsNull@6d21714c)">
but was not.
```

#### Example

	public static class ToStringIsNull {
		@Override
		public String toString() {
			return null;
		}
	}

	@Test
	public void testIsEqualTo() {
		Object actual = null;
		Assertions.assertThat(actual).isEqualTo(new ToStringIsNull());
	}
	
	@Test
	public void testIsEqualTo_reversed() {
		Object actual = new ToStringIsNull();
		Assertions.assertThat(actual).isEqualTo(null);
	}

#### Java 8 specific ?

* NO  : create Pull Request from the `2.x` branch

I'll create a pull request for that issue.

**Comment by PascalSchumacher** [comment]
Thanks for reporting and for the pull request! 👍
